name: musicplayer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  external_path: ^2.0.1
  flutter:
    sdk: flutter
  flutter_advanced_drawer: ^1.3.7
  google_fonts: ^6.2.1
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
